### ISSUE TITLE
Image zoom problem

### ISSUE THREAD

**Issue by bones7242** [lbryio/spee.ch-components#1]
When trying to zoom in on an image, the spee.ch text below gets bigger, but the image does not.
https://spee.ch/0/dev-chat.jpeg

**Comment by Invariant-Change** [comment]
## Re: `calc(100vh - 3em); is a conflict of interest`

- **em** = Relative to the font-size of the element.
- **vh** = Relative to 1% of the height of the viewport.

This means the image can only be as big as **100%** of the screen size minus **3em** of the text size.

So when you **zoom** in, the image **shrinks** by the same em **increments** that the text **increases**, and because of the max height is 100vh, which is 100% of the screen size, it **never** zooms bigger.

It would be best to leave resizing natively to the browser. Most browsers do a good job with images, initially putting 100% of it in view with a zoom button to make it 100% of the image size while retaining the screen zoom in and out functionality.

And as @kauffj pointed out, the image size should be included in the HTML for improved speed and better image control.

Hope that helps :)

**Comment by Invariant-Change** [comment]
As for the "**Hosted via Spee.ch**" part not interfering with the screen/image size and adding scrollbars, this would work nicely...

```css 
a#asset-boilerpate {
    position: fixed;
    right: 5%;
    bottom: 5%;
    background: #444;
    padding: 4px 11px;
    color: #0affbd;
    border-radius: 3px;
    border: 1px solid #555;
}
```
